import type { Scene } from '../types';

export const metroLastTrainScenes: Scene[] = [
  {
    id: 'm1_start',
    day: 1,
    time: 'night',
    title: 'Последний поезд',
    icon: 'fa-train-subway',
    location: 'Платформа',
    roomId: 'hallway',
    nearbyRooms: ['living-room'],
    text: [
      'Ты влетаешь на пустую платформу за минуту до закрытия метро.',
      'Последний поезд уже у дверей, но в туннеле слышен странный металлический скрежет.',
    ],
    choices: [
      { id: 'm1_c1', text: 'Запрыгнуть в поезд', nextSceneId: 'm1_wagon' },
      { id: 'm1_c2', text: 'Остаться на платформе', nextSceneId: 'm1_platform_wait' },
    ],
  },
  {
    id: 'm1_platform_wait',
    day: 1,
    time: 'latenight',
    title: 'Слишком тихо',
    icon: 'fa-triangle-exclamation',
    location: 'Платформа',
    roomId: 'hallway',
    nearbyRooms: [],
    text: [
      'Поезд уходит, свет на станции мигает и гаснет.',
      'Из туннеля раздается шепот, и шаги приближаются слишком быстро.',
    ],
    choices: [],
    isGameOver: true,
  },
  {
    id: 'm1_wagon',
    day: 1,
    time: 'latenight',
    title: 'Пустой вагон',
    icon: 'fa-chair',
    location: 'Вагон №7',
    roomId: 'living-room',
    nearbyRooms: ['kitchen', 'hallway'],
    text: [
      'В вагоне нет никого, кроме кондуктора в конце салона.',
      'Над дверью мигает табло: "Не смотри в окно после третьей остановки".',
    ],
    choices: [
      { id: 'm2_c1', text: 'Сесть ближе к кондуктору', nextSceneId: 'm2_conductor' },
      { id: 'm2_c2', text: 'Сесть у окна', nextSceneId: 'm2_window' },
    ],
  },
  {
    id: 'm2_window',
    day: 1,
    time: 'latenight',
    title: 'Отражение',
    icon: 'fa-eye',
    location: 'Вагон №7',
    roomId: 'living-room',
    nearbyRooms: [],
    text: [
      'В окне отражается не твое лицо.',
      'Поезд останавливается между станциями, и отражение улыбается первым.',
    ],
    choices: [],
    isGameOver: true,
  },
  {
    id: 'm2_conductor',
    day: 1,
    time: 'latenight',
    title: 'Инструкция',
    icon: 'fa-id-badge',
    location: 'Вагон №7',
    roomId: 'kitchen',
    nearbyRooms: ['living-room'],
    text: [
      'Кондуктор шепчет: "Когда свет погаснет, не вставай и не отвечай на голос по громкой связи".',
      'Через секунду лампы уходят в полную темноту.',
    ],
    choices: [
      {
        id: 'm3_c1',
        text: 'Сидеть молча до остановки',
        nextSceneId: 'm3_exit',
        setFlags: { obeyed_conductor: true },
      },
      { id: 'm3_c2', text: 'Ответить на голос по громкой связи', nextSceneId: 'm3_intercom' },
    ],
  },
  {
    id: 'm3_intercom',
    day: 1,
    time: 'latenight',
    title: 'Нарушение',
    icon: 'fa-skull',
    location: 'Вагон №7',
    roomId: 'kitchen',
    nearbyRooms: [],
    text: [
      'Голос по громкой связи повторяет твое имя, а двери открываются в стену туннеля.',
      'Кто-то тянет тебя наружу за воротник.',
    ],
    choices: [],
    isGameOver: true,
  },
  {
    id: 'm3_exit',
    day: 1,
    time: 'morning',
    title: 'Финал',
    icon: 'fa-sun',
    location: 'Станция "Рассвет"',
    roomId: 'hallway',
    nearbyRooms: ['living-room'],
    text: [
      'Поезд останавливается на пустой станции, где уже светает.',
      'Кондуктор кивает: "Ты слушал правила. Поэтому доехал".',
    ],
    choices: [],
    isVictory: true,
  },
];
